samples    :                  "docs/samples.csv"
basecall   :
    threads  :                32
    memory   :                16000
    container:                "analysis/containers/guppycpu.simg"

demultiplex:
    threads  :                16
    container:                "shub://mbhall88/Singularity_recipes:deepbinnercpu@e4b1f8c8539516b85a765cce97ce0422"

trim       :
    threads  :                16
    memory   :                8000
    container:                "docker://quay.io/biocontainers/porechop:0.2.3_seqan2.1.1--py36h2d50403_3"

download_decontamination_db:
    perl_script :             "analysis/scripts/make_pipeline_reference_files.pl"
    out_dir :                 "data/decontamination_db/"

index_decontamination_db:
    split  :                  "10G"
    container:                "docker://quay.io/biocontainers/minimap2:2.15--h84994c4_1"

mapping:
    threads:                  16
    memory:                   16000
    container:                "docker://quay.io/biocontainers/minimap2:2.15--h84994c4_1"

sort:
    threads:                  16
    memory:                   4000
    container:                "docker://quay.io/biocontainers/samtools:1.9--h57cc563_6"

index_bams:
    memory:                   300
    container:                "docker://quay.io/biocontainers/samtools:1.9--h57cc563_6"

filter:
    container:                "docker://continuumio/miniconda3"

mykrobe:
    memory:                   1500
    container:                "shub://mbhall88/Singularity_recipes:mykrobe@42b5d17d11b08db0df5ee21dd12bc1f0"
    species:                  "tb"
    output_format:            "json"

generate_krona_input:
    container:                "docker://continuumio/miniconda3"

plot_sample_composition:
    container:                "docker://quay.io/biocontainers/krona:2.7--pl526_2"

qc_plot:
    memory:                   8000
    container:                "shub://mbhall88/Singularity_recipes:pistis@c0161afb485b937f58e38f7bf16c7966"
