samples    :   "docs/samples.csv"
basecall   :
    threads  : 32
    memory   : 16000
    container: "analysis/containers/guppycpu.simg"

demultiplex:
    threads  : 16
    memory   : 16000
    container: "shub://mbhall88/Singularity_recipes:deepbinnercpu"

trim       :
    threads  : 16
    memory   : 8000
    container: "docker://quay.io/biocontainers/porechop:0.2.3_seqan2.1.1--py36h2d50403_3"
