channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - mamba
  - snakemake>=6
  - bcftools=1.12
  - samtools=1.12
  - snakefmt
  - pandas=1.2
  - ripgrep=12.1
  - jupyter
  - seaborn=0.11
  - matplotlib-base=3
  - upsetplot=0.5