samplesheet:          "../../docs/samplesheet.csv"
compass_vcf_dir:      "illumina/gvcfs"
asm_dir:              "../assembly/results"
data_dir:             "../../data/QC/subsampled"
genome_size:          4411532
h37rv:
  genome:     "resources/h37rv.fa"
  mask:       "resources/compass-mask.bed"
containers:
  conda:       "docker://continuumio/miniconda3:4.7.12"
  bcftools:    "docker://quay.io/biocontainers/bcftools:1.10.2--hd2cd319_0"
  varifier:    "docker://mbhall88/varifier:3cf8372"
envs:
  aln_tools:           "envs/aln_tools.yaml"
  filter:              "envs/filter.yaml"
  varifier:            "envs/varifier.yaml"
  concordance:         "envs/concordance.yaml"
  plot_concordance:    "envs/plot_concordance.yaml"
  plot_truth_eval:     "envs/plot_truth_eval.yaml"
scripts:
  filter:           "scripts/apply_filters.py"
  concordance:      "scripts/concordance.py"
  plot_concordance: "scripts/plot_concordance.py"
  plot_truth_eval:  "scripts/plot_truth_eval.py"

# filters for nanopore bcftools calls
filters:
  min_depth:       0
  max_depth:       0
  min_qual:        60
  min_strand_bias: 0
  min_bqb:         0
  min_mqb:         0
  min_rpb:         0.05
  max_sgb:         -0.50
  min_vdb:         0.002

assemblies:
  mada_101:  "flye"
  mada_102:  "canu"
  mada_104:  "flye"
  mada_130:  "flye"
  mada_116:  "flye"
  mada_1-44: "flye"
  mada_132:  "flye"
  mada_125:  "spades"
