$schema:                        "http://json-schema.org/draft-07/schema#"

description:                    snakemake configuration file

type:                           object

properties:

  samples:
    type:                       string

  basecall:
    type:                       object
    properties:
        threads:
            type:               number
            default:            1
        memory:
            type:               number
            default:            4000
        container:
            type:               string
    required:
        - container

  demultiplex:
    type:                       object
    properties:
        threads:
            type:               number
            default:            1
        memory:
            type:               number
            default:            4000
        container:
            type:               string
    required:
        - container

  trim:
    type:                       object
    properties:
        threads:
            type:               number
            default:            1
        memory:
            type:               number
            default:            4000
        container:
            type:               string
    required:
        - container

  download_decontamination_db:
    type:                       object
    properties:
        threads:
            type:               number
            default:            1
        memory:
            type:               number
            default:            1000
        perl_script:
            type:               string
        out_dir:
            type:               string
    required:
        - perl_script
        - out_dir

  index_decontamination_db:
    type:                       object
    properties:
        memory:
            type:               number
            default:            16000
        preset:
            type:               string
            default:            "map-ont"
        split:
            type:               string
            default:            "4G"
        container:
            type:               string
    required:
        - container

  mapping:
    type:                       object
    properties:
        memory:
            type:               number
            default:            4000
        threads:
            type:               number
            default:            1
        container:
            type:               string
    required:
        - container

  sort:
    type:                       object
    properties:
        memory:
            type:               number
            default:            1000
        threads:
            type:               number
            default:            1
        container:
            type:               string
    required:
        - container

  index_bams:
    type:                       object
    properties:
        memory:
            type:               number
            default:            1000
        threads:
            type:               number
            default:            1
        container:
            type:               string
    required:
        - container

  filter:
    type:                       object
    properties:
        memory:
            type:               number
            default:            1000
        threads:
            type:               number
            default:            1
        container:
            type:               string
    required:
        - container

  mykrobe:
    type:                       object
    properties:
        memory:
            type:               number
            default:            1000
        threads:
            type:               number
            default:            1
        container:
            type:               string
        species:
            type:               string
        output_format:
            type:               string
            patter:             "json|csv"
    required:
        - container
        - species
        - output_format

  generate_krona_input:
    type:                       object
    properties:
        memory:
            type:               number
            default:            500
        threads:
            type:               number
            default:            1
        container:
            type:               string
    required:
        - container

  plot_sample_composition:
    type:                       object
    properties:
        memory:
            type:               number
            default:            500
        threads:
            type:               number
            default:            1
        container:
            type:               string
    required:
        - container

required:
  - samples
  - basecall
  - demultiplex
  - trim
  - download_decontamination_db
  - index_decontamination_db
  - mapping
  - sort
  - index_bams
  - filter
  - mykrobe
  - generate_krona_input
  - plot_sample_composition
