$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  basecall:
    type: object
    properties:
        threads:
            type: number
            default: 1
        memory:
            type: number
            default: 4000
        container:
            type: string
    required:
        - container
  demultiplex:
    type: object
    properties:
        threads:
            type: number
            default: 1
        memory:
            type: number
            default: 4000
        container:
            type: string
    required:
        - container

required:
  - samples
  - basecall
  - demultiplex
