data_dir:    "/nfs/research/zi/mbhall/tech_wars/data"
asm_dir:     "../../analysis/assembly/results"
samplesheet: "../samples.paper.csv"
containers:
  base:   "docker://bash:5.1"
  seqkit: "docker://quay.io/biocontainers/seqkit:2.1.0--h9ee0642_0"
  curl:   "docker://curlimages/curl:7.80.0"
