samplesheet:        "../../docs/samplesheet.csv"
baseline_dir:       "../baseline_variants"
pandora_dir:        "../pandora_variants"
qc_dir:             "../../data/QC"
adaptive_threshold: 100
thresholds:
  - 0
  - 2
  - 5
  - 12

nanopore_callers:
  - pandora_map
  - pandora_compare
  - bcftools

containers:
  conda: "docker://continuumio/miniconda3:4.7.12"

envs:
  dotplot:           "envs/dotplot.yaml"
  plot_concordance:  "envs/plot_concordance.yaml"
  clustering:        "envs/clustering.yaml"
  mixed_simulations: "envs/mixed_simulations.yaml"

scripts:
  dotplot:           "scripts/distance_dot_plot.py"
  plot_concordance:  "scripts/plot_concordance.py"
  clustering:        "scripts/clustering.py"
  mixed_simulations: "scripts/mixed_simulations.py"

bcftools_clustering_thresholds:
  0:  0
  2:  2
  5:  5
  12: 11

compare_clustering_thresholds:
  0:  0
  2:  1
  5:  3
  12: 7