samplesheet:          "../../docs/samplesheet.csv"
build_prg_dir:        "../../data/H37Rv_PRG"
baseline_variant_dir: "../baseline_variants"
qc_dir:               "../../data/QC"
compass_vcf_dir:      "illumina/gvcfs"
asm_dir:              "../assembly/results"
data_dir:             "../../data/QC/subsampled"
genome_size:          4411532
h37rv:
  genome: "../../data/H37Rv_PRG/resources/h37rv.fa"
  mask:   "../../data/H37Rv_PRG/resources/compass-mask.bed"
containers:
  conda:     "docker://continuumio/miniconda3:4.7.12"
  pandora:   "docker://quay.io/mbhall88/pandora:95f5fb3"
  bcftools:  "docker://quay.io/biocontainers/bcftools:1.10.2--hd2cd319_0"
  varifier:  "docker://mbhall88/varifier:3cf8372"
  snp-dists: "docker://quay.io/biocontainers/snp-dists:0.7.0--hed695b0_0"
  make_prg:  "library://mbhall88/default/make_prg:0bb4a27"
envs:
  update_msas:     "envs/update_msas.yaml"
  fd:              "envs/fd.yaml"
  normalise_pos:   "envs/normalise_pos.yaml"
  plot_truth_eval: "envs/plot_truth_eval.yaml"
  filter:          "envs/filter.yaml"
  varifier:        "envs/varifier.yaml"
scripts:
  update_msas:     "scripts/update_msas.py"
  make_prg:        "../../data/H37Rv_PRG/scripts/build_local_prgs.sh"
  normalise_pos:   "scripts/normalise_pos.py"
  plot_truth_eval: "scripts/plot_truth_eval.py"
  filter:          "scripts/apply_filters.py"

# filters for pandora calls
filters:
  min_covg:        0
  max_covg:        0
  min_gt_conf:     0
  min_strand_bias: 0
  max_gaps:        0

assemblies:
  mada_101:  "flye"
  mada_102:  "flye"
  mada_104:  "flye"
  mada_130:  "flye"
  mada_116:  "flye"
  mada_1-44: "flye"
  mada_132:  "flye"
  mada_125:  "flye"

pandora_k:            15  # kmer size for pandora
pandora_w:            14  # window size for pandora
prg_names:
  - sparse
  - dense
nesting_level:        5  # for make_prg
match_length:         7  # for make_prg
discover:
  merge_dist:        22
  max_candidate_len: 30
  min_dbg_abundance: 2
