samplesheet:          "../../docs/samplesheet.csv"
build_prg_dir:        "../../data/H37Rv_PRG"
qc_dir:               "../../data/QC"
compass_vcf_dir:      "illumina/gvcfs"
asm_dir:              "../assembly/results"
data_dir:             "../../data/QC/subsampled"
genome_size:          4411532
h37rv:
  genome:     "resources/h37rv.fa"
  mask:       "resources/compass-mask.bed"
containers:
  conda:       "docker://continuumio/miniconda3:4.7.12"
  pandora:     "docker://quay.io/mbhall88/pandora:47b8e8c"
  bcftools:    "docker://quay.io/biocontainers/bcftools:1.10.2--hd2cd319_0"
  varifier:    "docker://mbhall88/varifier:3cf8372"
  snp-dists:   "docker://quay.io/biocontainers/snp-dists:0.7.0--hed695b0_0"
envs:
  update_msas: "envs/update_msas.yaml"
scripts:
  update_msas: "scripts/update_msas.py"

# filters for nanopore bcftools calls
filters:
  min_depth:       0
  max_depth:       0
  min_qual:        60
  min_strand_bias: 0
  min_bqb:         0
  min_mqb:         0
  min_rpb:         0.05
  max_sgb:         -0.5
  min_vdb:         0.002

assemblies:
  mada_101:  "flye"
  mada_102:  "flye"
  mada_104:  "flye"
  mada_130:  "flye"
  mada_116:  "flye"
  mada_1-44: "flye"
  mada_132:  "flye"
  mada_125:  "flye"

pandora_k:            15  # kmer size for pandora
pandora_w:            14  # window size for pandora
prg_names:
  - sparse
  - dense
