samplesheet:       "../../docs/samplesheet.csv"
mykrobe_panel_url: "https://ndownloader.figshare.com/files/14120198"
match_len:         5  # make_prg minimum match length used in drprg build
padding:           100  # base padding to add to genes in drprg build
# filtering used on the pandora VCF in drprg
filters:
  min_covg:        3
  min_strand_bias: 0.01
  min_frs:         -1.0
  max_indel:       20
  min_gt_conf:
    nanopore: 15
    illumina: 30

containers:
  mykrobe: "docker://quay.io/biocontainers/mykrobe:0.9.0--py38h8e3bb3f_3"
  conda:   "docker://continuumio/miniconda3:4.9.2"
  drprg:   "docker://quay.io/mbhall88/drprg:7044f5f"
