data_dir: "/hps/nobackup/research/zi/projects/tech_wars/data"
outdir:   "results"
min_covg: 0.8  # Ignore reads with alignments shorter than min_covg * read length

fast5:
  indir:      "/hps/nobackup/research/zi/projects/tech_wars/data/madagascar/nanopore/raw_data/"  # directory containing all of the original fast5 files
  outdir:     "data/fast5s/"  # directory where fast5 reads used for training will be placed
  batch_size: 4000  # number of fast5 per multi-fast5
  trim:  # Number of samples to trim off start and end of fast5 training files
    start: 200
    end:   100

containers:
  conda:   "docker://continuumio/miniconda3:4.7.12"
  taiyaki: "library://mbhall88/default/taiyaki:ce0cfbf"
  fast5:   "docker://quay.io/biocontainers/ont-fast5-api:3.0.1--py_0"

envs:
  aln_tools: "envs/aln_tools.yaml"

assemblies:  # mada_1-2 is not being used as they are not of sufficient quality
  mada_101:  "/hps/nobackup/research/zi/projects/tech_wars/analysis/assembly/results/mada_101/flye/pacbio/polished_assembly.flye.pacbio.fasta"
  mada_102:  "/hps/nobackup/research/zi/projects/tech_wars/analysis/assembly/results/mada_102/spades/pacbio/polished_assembly.spades.pacbio.fasta"
  mada_104:  "/hps/nobackup/research/zi/projects/tech_wars/analysis/assembly/results/mada_104/flye/pacbio/polished_assembly.flye.pacbio.fasta"
  mada_116:  "/hps/nobackup/research/zi/projects/tech_wars/analysis/assembly/results/mada_116/unicycler/pacbio/decontam.assembly.unicycler.pacbio.fasta"
  mada_125:  "/hps/nobackup/research/zi/projects/tech_wars/analysis/assembly/results/mada_125/spades/pacbio/polished_assembly.spades.pacbio.fasta"
  mada_130:  "/hps/nobackup/research/zi/projects/tech_wars/analysis/assembly/results/mada_130/flye/pacbio/decontam.assembly.flye.pacbio.fasta"
  mada_132:  "/hps/nobackup/research/zi/projects/tech_wars/analysis/assembly/results/mada_132/spades/pacbio/polished_assembly.spades.pacbio.fasta"
  mada_1-44: "/hps/nobackup/research/zi/projects/tech_wars/analysis/assembly/results/mada_1-44/unicycler/pacbio/decontam.assembly.unicycler.pacbio.fasta"
