data_dir:    "/hps/nobackup/research/zi/projects/tech_wars/data"
outdir:      "results"
genome_size: 4411532
h37rv:
  genome:     "resources/h37rv.fa"
  annotation: "resources/h37rv.gbk"
  features:   "resources/h37rv.gff3"
adapters:    "resources/TruSeq3-PE.fa"
containers:
  unicycler:   "docker://quay.io/biocontainers/unicycler:0.4.8--py37h8b12597_0"
  flye:        "docker://quay.io/biocontainers/flye:2.6--py37he513fc3_0"
  spades:      "docker://quay.io/biocontainers/spades:3.14.0--h2d02072_0"
  quast:       "/hps/nobackup/research/zi/gblackwell/assemble_all_ena.2019.02.251b36c597d63d8dd5020b0f68ac9cce3765cff14f.img"
  trimmomatic: "docker://quay.io/biocontainers/trimmomatic:0.39--1"
  racon:       "docker://quay.io/biocontainers/racon:1.4.10--he513fc3_0"
  minimap2:    "docker://quay.io/biocontainers/minimap2:2.17--h8b12597_1"
samples:
  - "mada_101"
#  - "mada_130"
#  - "mada_132"
#  - "mada_1-2"
